"""added new_newsletters table

Revision ID: 229254f83d52
Revises: 3c4a47daab59
Create Date: 2022-02-16 12:07:33.048687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229254f83d52'
down_revision = '3c4a47daab59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubrik', sa.String(length=100), nullable=False),
    sa.Column('underRubrik', sa.String(length=100), nullable=False),
    sa.Column('innehall', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_newsletters')
    # ### end Alembic commands ###
