"""added datum_skapad column i new_newsletters

Revision ID: f53c9b86709e
Revises: 229254f83d52
Create Date: 2022-02-16 12:20:18.902958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53c9b86709e'
down_revision = '229254f83d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_newsletters', sa.Column('datum_skapad', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_newsletters', 'datum_skapad')
    # ### end Alembic commands ###
